spring:
  application:
    name: velog-clone
  datasource:
    driver-class-name: org.h2.Driver
    #    url: jdbc:h2:mem:testdb;MODE=MYSQL
    #   intelliJ 내의 datasource 기능 이용하기 위해 file로 관리, 다중 접속 허용 설정
    url: jdbc:h2:file:./velog;MODE=MYSQL;AUTO_SERVER=TRUE
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

## logging
logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG